import test from 'node:test';
import assert from 'node:assert/strict';
import {newRoom,applyAction,publicRoom,goMove,goScore,configFrom} from '../lib/game-engine.ts';
const users=Array.from({length:13},(_,i)=>({id:'p'+i,name:'玩家'+i}));
const config=(game,capacity=2)=>({game,capacity,rounds:3,boardSize:9});
function room(game='gomoku',count=2){const r=newRoom('TESTROOM','测试房间',config(game,count),users[0]);for(let i=1;i<count;i++)applyAction(r,users[i],{type:'join'});return r;}
function start(r){for(const u of users.slice(1,r.config.capacity))applyAction(r,u,{type:'ready'});applyAction(r,users[0],{type:'start'});}
test('config rejects invalid games, capacity, rounds and board size',()=>{for(const c of [{...config('gomoku'),capacity:3},{...config('werewolf',5)},{...config('go'),rounds:0},{...config('go'),boardSize:8},{...config('__proto__')}])assert.throws(()=>configFrom(c));});
test('switching 8-player room to board game preserves every member and promotes seats on expansion',()=>{const r=room('werewolf',8);start(r);applyAction(r,users[0],{type:'configure',config:config('gomoku'),name:r.name});assert.equal(r.members.length,8);assert.equal(r.members.filter(p=>p.seat!==null).length,2);assert.equal(r.members.filter(p=>p.seat===null).length,6);assert.equal(r.match,null);applyAction(r,users[0],{type:'configure',config:config('undercover',8),name:r.name});assert.equal(r.members.filter(p=>p.seat!==null).length,8);});
test('only host can configure and start, other players must ready',()=>{const r=room();assert.throws(()=>applyAction(r,users[1],{type:'configure',config:config('go'),name:r.name}),/房主/);assert.throws(()=>applyAction(r,users[0],{type:'start'}),/准备/);assert.throws(()=>applyAction(r,users[1],{type:'start'}),/房主/);});
test('late joins are spectators and cannot play; host migrates on leave',()=>{const r=room();start(r);applyAction(r,users[2],{type:'join'});assert.equal(r.members[2].seat,null);assert.throws(()=>applyAction(r,users[2],{type:'move',index:0}),/旁观/);applyAction(r,users[0],{type:'leave'});assert.equal(r.host,users[1].id);assert.equal(r.match,null);});
test('gomoku turn checks and five-in-row victory update scores',()=>{const r=room();start(r);assert.throws(()=>applyAction(r,users[1],{type:'move',index:0}),/轮到/);for(let i=0;i<4;i++){applyAction(r,users[0],{type:'move',index:i});applyAction(r,users[1],{type:'move',index:15+i});}applyAction(r,users[0],{type:'move',index:4});assert.equal(r.match.phase,'finished');assert.equal(r.scores.p0,1);start(r);assert.equal(r.match.turn,'p1');assert.equal(r.round,2);});
test('tic tac toe detects a draw',()=>{const r=room('tictactoe');start(r);[0,1,2,4,3,5,7,6,8].forEach((index,i)=>applyAction(r,users[i%2],{type:'move',index}));assert.equal(r.match.phase,'finished');assert.equal(r.match.winners.length,0);});
test('go captures surrounded stone and rejects suicide and repetition',()=>{const b=[0,1,0,1,2,1,0,0,0];const move=goMove(b,7,1,3,[]);assert.equal(move.board[4],0);assert.equal(move.taken,1);assert.throws(()=>goMove([0,2,0,2,0,2,0,2,0],4,1,3,[]),/自杀/);assert.throws(()=>goMove(b,7,1,3,[move.key]),/同形/);});
test('go double pass scores with komi',()=>{const r=room('go');start(r);applyAction(r,users[0],{type:'pass'});applyAction(r,users[1],{type:'pass'});assert.equal(r.match.phase,'finished');assert.equal(r.match.winners[0],'p1');assert.deepEqual(goScore(Array(9).fill(1),3),[9,7.5]);});
test('undercover hides roles and other words, watcher receives no secret',()=>{const r=room('undercover',6);start(r);applyAction(r,users[6],{type:'join'});const view=publicRoom(r,'p0');assert.equal(view.secret.role,null);assert.ok(view.secret.word);assert.equal(view.match.roles,undefined);assert.equal(view.match.words,undefined);assert.equal(view.match.votes,undefined);assert.equal(publicRoom(r,'p6').secret,null);});
test('undercover sequential discussion and vote reaches civilian victory',()=>{const r=room('undercover',4);start(r);const spy=r.match.players.find(id=>r.match.roles[id]==='卧底');assert.throws(()=>applyAction(r,users[1],{type:'speak',text:'测试发言'}),/等待/);for(let i=0;i<4;i++)applyAction(r,users[i],{type:'speak',text:'描述'+i});assert.equal(r.match.phase,'vote');for(let i=0;i<4;i++)applyAction(r,users[i],{type:'vote',target:users[i].id===spy?'p0'===spy?'p1':'p0':spy});assert.equal(r.match.phase,'finished');assert.match(r.match.result,/平民获胜/);});
test('werewolf night role permissions and private seer results',()=>{const r=room('werewolf',6);start(r);const m=r.match;const wolves=users.filter(u=>m.roles[u.id]==='狼人');const seer=users.find(u=>m.roles[u.id]==='预言家');const witch=users.find(u=>m.roles[u.id]==='女巫');const victim=users.find(u=>m.roles[u.id]==='村民');assert.throws(()=>applyAction(r,seer,{type:'vote',target:victim.id}),/狼人行动/);wolves.forEach(u=>applyAction(r,u,{type:'vote',target:victim.id}));assert.equal(m.phase,'seer');applyAction(r,seer,{type:'inspect',target:wolves[0].id});assert.equal(m.phase,'witch');assert.ok(publicRoom(r,seer.id).secret.notes[0].includes('狼人'));assert.equal(publicRoom(r,witch.id).secret.notes.length,0);assert.equal(publicRoom(r,witch.id).secret.victim,victim.id);assert.equal(publicRoom(r,victim.id).secret.victim,null);applyAction(r,witch,{type:'witch',choice:'save'});assert.equal(m.phase,'discussion');assert.equal(m.alive.length,6);assert.equal(m.potions.save,false);});
test('finished game may reset rounds; deliberate spectator stays spectator',()=>{const r=room();applyAction(r,users[2],{type:'join',watch:true});applyAction(r,users[0],{type:'configure',config:config('undercover',3),name:r.name});assert.equal(r.members[2].seat,null);});
