"use client";
import { useCallback, useEffect, useRef, useState } from 'react';
import { Gamepad2, LayoutGrid, Plus, ArrowUpRight, Users, SlidersHorizontal, Pencil, Sparkles, Radio, DoorOpen, Eye, Crown, RefreshCw, Search, X, LoaderCircle } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { ConfigFields, games, initialConfig, Picker } from './game-ui';
import { RoomView } from './room-view';
import { type Action, type Config, type PublicRoom, type RoomSummary, type GameType } from '@/lib/game-engine';
type User={id:string;name:string};
type ApiResult={user:User;rooms?:RoomSummary[];room?:PublicRoom|null;error?:string};
async function api(action?:Action,room?:string):Promise<ApiResult>{
 const response=await fetch('/api/play'+(room?'?room='+encodeURIComponent(room):''),action?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action)}:{cache:'no-store'});
 const data=await response.json() as ApiResult;if(!response.ok)throw new Error(data.error||'请求失败，请重试');return data;
}
export default function Home(){
 const [filter,setFilter]=useState('all'),[create,setCreate]=useState(false),[profile,setProfile]=useState(false),[filterOpen,setFilterOpen]=useState(false),[sort,setSort]=useState('newest'),[capacity,setCapacity]=useState('all'),[vacant,setVacant]=useState(false),[status,setStatus]=useState('all'),[query,setQuery]=useState('');
 const [user,setUser]=useState<User|null>(null),[rooms,setRooms]=useState<RoomSummary[]>([]),[room,setRoom]=useState<PublicRoom|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [draftName,setDraftName]=useState(''),[roomName,setRoomName]=useState(''),[config,setConfig]=useState<Config>(initialConfig);
 const roomRef=useRef<PublicRoom|null>(null),epoch=useRef(0),busyRef=useRef(false),bootstrap=useRef<Promise<ApiResult>|null>(null);
 const installRoom=useCallback((value:PublicRoom|null)=>{roomRef.current=value;setRoom(value);history.replaceState(null,'',value?'/?room='+value.id:'/');},[]);
 const refresh=useCallback(async()=>{const started=epoch.current;const id=roomRef.current?.id;try{const d=await api(undefined,id);if(started!==epoch.current||busyRef.current)return;setUser(d.user);if(d.rooms)setRooms(d.rooms);if(d.room)setRoom(d.room);setError('');}catch(e){if(started===epoch.current)setError(e instanceof Error?e.message:'连接暂时中断');}finally{setLoading(false);}},[]);
 const act=useCallback(async(a:Action)=>{if(busyRef.current)return false;busyRef.current=true;setBusy(true);epoch.current++;try{const d=await api({...a,...(roomRef.current?{room:roomRef.current.id}:{})});setUser(d.user);if(Object.hasOwn(d,'room'))installRoom(d.room??null);setError('');if(a.type==='profile'){toast.success('昵称已更新');}if(a.type==='configure')toast.success('房间设置已更新，所有成员已保留');return true;}catch(e){toast.error(e instanceof Error?e.message:'操作失败，请重试');return false;}finally{epoch.current++;busyRef.current=false;setBusy(false);}},[installRoom]);
 useEffect(()=>{let active=true;const init=async()=>{try{bootstrap.current??=api();const d=await bootstrap.current;if(!active)return;setUser(d.user);setRooms(d.rooms??[]);const link=new URLSearchParams(location.search).get('room');if(link&&/^[A-Fa-f0-9]{8}$/.test(link)){await act({type:'join',room:link.toUpperCase()});}}catch(e){if(active)setError(e instanceof Error?e.message:'联机服务暂时不可用');}finally{if(active)setLoading(false);}};void init();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{if(active&&!busyRef.current)await refresh();if(active)timer=setTimeout(poll,document.hidden?8000:roomRef.current?1200:4000);};timer=setTimeout(poll,4000);return()=>{active=false;clearTimeout(timer);};},[act,refresh]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'list_game_rooms',description:'Read the available multiplayer rooms in this lobby.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({rooms:(await api()).rooms})},{name:'start_room_creation',description:'Open the create room dialog. This does not create a room.',inputSchema:{type:'object',properties:{game:{type:'string',enum:games.map(g=>g.id)}},required:['game'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const game=(input as {game?:GameType})?.game;if(!games.some(g=>g.id===game))throw new Error('Invalid game');if(roomRef.current)throw new Error('Leave the current room first');setConfig({...initialConfig,game:game!,capacity:game==='werewolf'?8:game==='undercover'?6:2});setCreate(true);return {dialog:'create-room',game};}}];tools.forEach(tool=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}});return()=>lifecycle.abort();},[]);
 const openCreate=()=>{setRoomName('');setConfig({...initialConfig,game:filter==='all'?'gomoku':filter as GameType,capacity:filter==='werewolf'?8:filter==='undercover'?6:2});setCreate(true);};
 const join=async(id:string,watch=false)=>{await act({type:'join',room:id,watch});};
 const share=()=>{const link=location.origin+'/?room='+room?.id;void navigator.clipboard.writeText(link).then(()=>toast.success('邀请链接已复制，发给朋友就能入座')).catch(()=>toast.info('邀请链接：'+link,{duration:15000}));};
 const filtered=rooms.filter(r=>(filter==='all'||r.config.game===filter)&&(capacity==='all'||capacity==='2'?capacity==='all'||r.config.capacity===2:capacity==='small'?r.config.capacity>=3&&r.config.capacity<=6:r.config.capacity>=7)&&(!vacant||(!r.playing&&r.players<r.config.capacity))&&(status==='all'||(status==='waiting'?!r.playing:r.playing))&&(!query||r.name.includes(query)||r.id.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==='players-desc'?b.players-a.players:sort==='players-asc'?a.players-b.players:sort==='vacancies'?(b.config.capacity-b.players)-(a.config.capacity-a.players):b.created-a.created);
 const totalPlayers=rooms.reduce((sum,r)=>sum+r.players+r.watchers,0);const filterCount=Number(capacity!=='all')+Number(vacant)+Number(status!=='all');
 return <div className="app-shell"><Toaster theme="dark" position="top-center"/><aside className="sidebar"><a className="brand" href="/" onClick={e=>{if(room){e.preventDefault();toast.info('请使用房间内的“返回大厅”离开房间');}}}><span className="brand-mark"><Gamepad2 size={25}/></span><strong>同桌<span>PLAYROOM</span></strong></a><div className="side-label">一起玩，更好玩</div><button className={`side-item ${!room?'selected':''}`} onClick={()=>{if(room)toast.info('请使用房间内的“返回大厅”离开房间');else setFilter('all');}}><LayoutGrid size={19}/>游戏大厅</button><div className="side-label games-label">游戏分类</div>{games.map(g=><button aria-label={g.name} key={g.id} className={`side-item ${filter===g.id?'selected':''}`} onClick={()=>{if(room)toast.info('房主可在“房间设置”中切换游戏');else setFilter(g.id);}}><g.icon size={18}/>{g.name}</button>)}<div className="side-bottom"><Sparkles size={18}/><strong>快乐不必很复杂</strong><p>一张桌子，几个朋友。<br/>下一局，一起吗？</p><span>PLAYROOM / VOL. 01</span></div></aside><div className="main-shell"><header className="topbar"><div className="breadcrumb">PLAYROOM<span>/</span><b>{room?'游戏房间':'游戏大厅'}</b></div><div className="top-actions"><span className={`connection ${error?'disconnected':''}`}><Radio size={14}/>{error?'正在重新连接':loading?'正在连接':room?'房间同步中':`${totalPlayers} 位玩家在房间`}</span><button className="profile" disabled={!user} onClick={()=>{setDraftName(user?.name??'');setProfile(true);}} aria-label="设置用户名称"><span className="avatar">{user?.name[0]??'玩'}</span><span>{user?.name??'正在入座'}</span><Pencil size={14}/></button></div></header>{error&&<div className="error-banner" role="alert"><span>{error}，正在尝试恢复连接。</span><button onClick={()=>void refresh()}><RefreshCw size={14}/>重试</button></div>}
 {room&&user?<RoomView room={room} user={user} busy={busy} act={act} share={share}/>:<main className="lobby"><div className="page-heading"><div><div className="eyebrow">GOOD TIMES, TOGETHER</div><h1>就差你入座了<span> ✳</span></h1><p>选个游戏，开张桌子，和朋友一起玩。</p></div><button className="primary" disabled={loading||!user} onClick={openCreate}><Plus size={18}/>创建房间</button></div><div className="section-heading"><h2>今天玩什么？</h2><span>五种游戏，无限好时光</span></div><div className="game-grid">{games.map(g=><button className={`game-card ${g.color} ${filter===g.id?'active':''}`} key={g.id} onClick={()=>setFilter(filter===g.id?'all':g.id)}><div className="game-card-top"><span>{g.en}</span><ArrowUpRight size={17}/></div><g.icon className="game-symbol" size={52} strokeWidth={1.4}/><h3>{g.name}</h3><p>{g.desc}</p><div className="game-card-bottom"><span><Users size={13}/>{g.people}</span><span>{rooms.filter(r=>r.config.game===g.id).length} 个房间</span></div></button>)}</div><section className="rooms-section"><div className="rooms-heading"><div><h2>房间大厅 <span className="count">{filtered.length}</span></h2><p>找个空位，认识新朋友</p></div><div className="room-filters"><button className={`secondary ${filterCount?'filtered':''}`} onClick={()=>setFilterOpen(true)}><SlidersHorizontal size={16}/>筛选{filterCount>0?` ${filterCount}`:''}</button><Picker label="房间排序" value={sort} onChange={setSort} options={[{value:'newest',label:'最新创建'},{value:'players-desc',label:'人数从多到少'},{value:'players-asc',label:'人数从少到多'},{value:'vacancies',label:'空位最多'}]}/><button className="icon-button" title="刷新大厅" aria-label="刷新大厅" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/></button></div></div><div className="room-toolbar"><div className="filter-chips"><button className={filter==='all'?'chip active':'chip'} onClick={()=>setFilter('all')}>全部游戏</button>{games.map(g=><button key={g.id} className={filter===g.id?'chip active':'chip'} onClick={()=>setFilter(g.id)}>{g.name}</button>)}</div><label className="room-search"><Search size={15}/><input aria-label="查找房间" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索房间 / 编号"/></label></div>
 {loading?<div className="empty-state" role="status"><LoaderCircle className="animate-spin" size={26}/><h3>正在连接游戏大厅…</h3></div>:error&&!rooms.length?<div className="empty-state"><Radio size={30}/><h3>暂时无法连接大厅</h3><p>请稍后重试，你的操作不会丢失。</p><button className="secondary" onClick={()=>void refresh()}>重新连接</button></div>:filtered.length?<div className="room-grid">{filtered.map(r=>{const g=games.find(g=>g.id===r.config.game)!;return <article className="room-card" key={r.id}><div className="room-card-head"><span className={`small-game-icon ${g.color}`}><g.icon size={20}/></span><span className="game-label">{g.name}</span><span className={`status-pill ${r.playing?'playing':''}`}>{r.playing?'游戏中':r.players>=r.config.capacity?'已满员':'等待加入'}</span></div><h3>{r.name}</h3><p className="room-id">#{r.id}<span>{r.config.rounds} 局{r.config.game==='go'?` · ${r.config.boardSize} 路`:''}</span></p><div className="room-host"><Crown size={13}/>{r.hostName}</div><div className="room-card-footer"><div><span><Users size={15}/><b>{r.players}</b> / {r.config.capacity}</span>{r.watchers>0&&<span className="room-watchers"><Eye size={13}/>{r.watchers}</span>}</div><button className={r.playing||r.players>=r.config.capacity?'join-button watch':'join-button'} disabled={busy} onClick={()=>join(r.id,r.playing||r.players>=r.config.capacity)}>{r.playing||r.players>=r.config.capacity?'进入旁观':'加入房间'}<ArrowUpRight size={15}/></button></div></article>})}</div>:<div className="empty-state"><DoorOpen size={32}/><h3>{rooms.length?'没有找到合适的房间':'第一张桌子，等你来开'}</h3><p>{rooms.length?'换个筛选条件，或者自己开一张桌子。':'创建一个房间，邀请朋友一起开始吧。'}</p><div className="empty-actions">{rooms.length>0&&<button className="secondary" onClick={()=>{setFilter('all');setCapacity('all');setVacant(false);setStatus('all');setQuery('');}}>清除筛选</button>}<button className="secondary" disabled={!user} onClick={openCreate}><Plus size={16}/>创建房间</button></div></div>}</section><footer><span>美好时光，正在连接</span><span>友好交流 · 认真游戏 · 开心就好</span></footer></main>}</div>
 <Dialog open={create} onOpenChange={setCreate}><DialogContent className="room-dialog"><DialogTitle>开一张桌子</DialogTitle><DialogDescription>选好游戏，邀请朋友一起入座。稍后也能在房间内更改。</DialogDescription><form onSubmit={async e=>{e.preventDefault();if(await act({type:'create',name:roomName,config}))setCreate(false);}}><ConfigFields name={roomName} setName={setRoomName} config={config} setConfig={setConfig}/><button disabled={busy||!roomName.trim()} className="primary form-submit" type="submit"><Plus size={17}/>{busy?'正在创建…':'创建房间'}</button></form></DialogContent></Dialog>
 <Dialog open={profile} onOpenChange={setProfile}><DialogContent><DialogTitle>大家怎么称呼你？</DialogTitle><DialogDescription>设置一个喜欢的名字，在大厅和游戏中展示。</DialogDescription><form className="config-fields" onSubmit={async e=>{e.preventDefault();if(await act({type:'profile',name:draftName}))setProfile(false);}}><label>用户名称<input autoComplete="nickname" maxLength={16} required value={draftName} onChange={e=>setDraftName(e.target.value)} placeholder="1–16 个字符"/></label><button disabled={busy||!draftName.trim()} className="primary form-submit">保存名称</button></form></DialogContent></Dialog>
 <Dialog open={filterOpen} onOpenChange={setFilterOpen}><DialogContent><DialogTitle>找到你的下一局</DialogTitle><DialogDescription>按游戏、人数和房间状态筛选，设置实时生效。</DialogDescription><div className="config-fields"><label>游戏类型<Picker value={filter} onChange={setFilter} label="筛选游戏类型" options={[{value:'all',label:'全部游戏'},...games.map(g=>({value:g.id,label:g.name}))]}/></label><label>房间人数上限<Picker value={capacity} onChange={setCapacity} label="筛选人数" options={[{value:'all',label:'不限人数'},{value:'2',label:'2 人 · 双人对弈'},{value:'small',label:'3–6 人 · 小聚'},{value:'large',label:'7–12 人 · 热闹开局'}]}/></label><label>房间状态<Picker value={status} onChange={setStatus} label="房间状态" options={[{value:'all',label:'全部状态'},{value:'waiting',label:'等待开局'},{value:'playing',label:'正在游戏'}]}/></label><label className="checkbox-row"><Checkbox checked={vacant} onCheckedChange={v=>setVacant(v===true)}/>仅显示可入座房间</label><div className="dialog-buttons"><button className="secondary" onClick={()=>{setFilter('all');setCapacity('all');setStatus('all');setVacant(false);}}>重置条件</button><button className="primary" onClick={()=>setFilterOpen(false)}>查看 {filtered.length} 个房间</button></div></div></DialogContent></Dialog>
 </div>;
}

